### PR TITLE
feat: devtool integration for slicemachine

### LINKED ISSUE #207: provide a devtools integration for slicemachine (and maybe more)
### Is your feature request related to a problem? Please describe.

We currently need to start the slicemachine in another terminal.

This could be a DX improvement to provide adevtool integration for prismic-nuxt

### Describe the solution you'd like

We could have:

- stop/stop slicemachine
- show slicemachine config
- why not a slicemachine iframe

### Additional context

- currently working on it :+1:

### PR DESCRIPTION
**Pull request by huang-julien**
## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
resolve #207 

Hey :wave: 
this PR provides a simple devtool integration for prismic. 

For now you can only start/stop the slicemachine and see the configuration. 

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [ ] All new and existing tests are passing.

### CODE REVIEW

**Comment by huang-julien** [comment]
we need to shamefully hoist in order to make devtools ui kit work properly :/ .

**Comment by huang-julien** [comment]
@lihbr  I think this is pretty much a good start for people to start contributing to the devtools integration. Any opinion on the UI ? I kept it very simple

**Review by lihbr — APPROVED** [review]
Awesome work and initiative @huang-julien ! I've rearranged dependencies a bit and tweaked code style but everything is mainly the same.

I also tried to get rid of some console warnings, still can't figure how to remove `[Vue Router warn]: No match found for location with path "/__prismic-client/_nuxt/"` when developing on the playground, but I checked it on the built artifact and its not there 🤷‍♀️

WS for HMR also seems broken but that looks like an issue on Vite's end perhaps (or something in between): 
image

Anyway, I'm happy to move forward with that version as a v0, can you check my changes and tell me if it's also a green light for you? Also sending you a little something over Discord~

🚀 💐

**Review by huang-julien — COMMENTED** [review]
Everything's working good 😄 It's a good start for people to improve it

**Pull request merged**
